=== AbraaoAlves/tsd/schema/tsd-config_v4.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"id": "tsd_config_v4",
	"type": "object",
	"required": ["version", "repo", "ref", "typingsPath"],
	"properties": {
		"version": {
			"type": "string",
			"enum": ["v4"]
		},
		"repo": {
			"type": "string"
		},
		"ref": {
			"type": "string"
		},
		"typingsPath": {
			"type": "string"
		},
		"installed": {
			"type": "object",
			"_______________patternProperties": {
				"^[\\S ]+$": {
					"type": "object",
					"required": ["repo", "key", "uri"],
					"properties": {
						"repo": {
							"type": "string"
						},
						"key": {
							"type": "string"
						},
						"uri": {
							"type": "string"
						}
					}
				}
			}
		}
	}
}

=== AbraaoAlves/tsd/test/modules/api/fixtures/expected/install/angularjs-angular/tsd.json
{
  "typingsPath": "D:\\_Editing\\github\\tsd\\tsd-origin\\test\\modules\\api\\tmp\\result\\install\\angularjs-angular\\typings",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "angularjs/angular.d.ts": {
      "commit": "3bc329f49a971b3dae92ca682cb81816dbe31a53",
      "blob": "c44f3408e4b90c2572045d231a91f6042cf2e8da"
    },
    "jquery/jquery.d.ts": {
      "commit": "3bc329f49a971b3dae92ca682cb81816dbe31a53",
      "blob": "99969f710e2dbcac67382988edc7224550d29b86"
    }
  }
}

=== AbraaoAlves/tsd/tsd-config.json
{
  "typingsPath": "tmp/typings_v4",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "angularjs/angular-cookies.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "01f2127ab06d220f4176c7c2a4f05e35"
    },
    "angularjs/angular-mocks.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "8a0be1acc847d342da5d5f62960fc951"
    },
    "angularjs/angular-resource.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "bfc89ea8ccee49184eb0e9775cb67fcf"
    },
    "angularjs/angular-sanitize.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "3989245163468ab7b98cb7b610bc950f"
    },
    "angularjs/angular-scenario.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "95c07431802c07892b23a150e6c18b9b"
    },
    "angularjs/angular.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "b28995eca15c5c5a3215e554f7a23b74"
    },
    "jquery/jquery.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "daee672de4bb1330b0c3d8fcdea04c82"
    },
    "async/async.d.ts": {
      "commit": "9653895ef1f7d5051d3c059b4ab683a1ca7d8420",
      "hash": "fb3987f1fae34dd648c82319b8cf983b"
    }
  }
}

=== AbraaoAlves/tsd/test/modules/api/fixtures/expected/install/angular-cookies/tsd.json
{
  "typingsPath": "typings",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "angularjs/angular-cookies.d.ts": {
      "commit": "c2df10e5f1b18fdd0b561da0a8804e4d534c59ed",
      "blob": "4dc2e038e13b2a7e71f338076f4875228e9027cf"
    },
    "jquery/jquery.d.ts": {
      "commit": "c2df10e5f1b18fdd0b561da0a8804e4d534c59ed",
      "blob": "99969f710e2dbcac67382988edc7224550d29b86"
    },
    "angularjs/angular.d.ts": {
      "commit": "c2df10e5f1b18fdd0b561da0a8804e4d534c59ed",
      "blob": "e76c2be094981c2852bd70a9c3fcbc7f99ff9c8f"
    }
  }
}

=== AbraaoAlves/tsd/test/modules/api/fixtures/command/install/angularjs-angular/tsd.json
{
  "typingsPath": "D:\\_Editing\\github\\tsd\\tsd-origin\\test\\modules\\api\\tmp\\command\\install\\angularjs-angular\\typings",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "jquery/jquery.d.ts": {
      "commit": "a8d8c2ac668fbb99cb60fb5d25c663e9356fee14",
      "blob": "99969f710e2dbcac67382988edc7224550d29b86"
    },
    "angularjs/angular.d.ts": {
      "commit": "a8d8c2ac668fbb99cb60fb5d25c663e9356fee14",
      "blob": "c44f3408e4b90c2572045d231a91f6042cf2e8da"
    }
  }
}

=== AbraaoAlves/tsd/test/modules/api/fixtures/command/install/async/tsd.json
{
  "typingsPath": "D:\\_Editing\\github\\tsd\\tsd-origin\\test\\modules\\api\\tmp\\command\\install\\async\\typings",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "async/async.d.ts": {
      "commit": "a8d8c2ac668fbb99cb60fb5d25c663e9356fee14",
      "blob": "5ba56e0dbb7cc433d5b98ab3cbbf5e0d92954ff1"
    }
  }
}

=== AbraaoAlves/tsd/tsd.json
{
  "typingsPath": "typings",
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "installed": {
    "colors/colors.d.ts": {
      "commit": "6b5f41cf318dd6c32fc405067e63921dcd447768",
      "blob": "c87112d7c4a1e0d113093d78501529b1839aec21"
    },
    "async/async.d.ts": {
      "commit": "6b5f41cf318dd6c32fc405067e63921dcd447768",
      "blob": "5ba56e0dbb7cc433d5b98ab3cbbf5e0d92954ff1"
    },
    "mocha/mocha.d.ts": {
      "commit": "6b5f41cf318dd6c32fc405067e63921dcd447768",
      "blob": "8c1167def1f42112e0476902389dcac13809f7ec"
    },
    "node/node.d.ts": {
      "commit": "6b5f41cf318dd6c32fc405067e63921dcd447768",
      "blob": "9ae2d75aedcc82a0b53b3a37c442629d6da50575"
    },
    "underscore/underscore.d.ts": {
      "commit": "6b5f41cf318dd6c32fc405067e63921dcd447768",
      "blob": "cd7a2867e5a04b13f6d6143b87e519e8f28a6062"
    },
    "angularjs/angular-cookies.d.ts": {
      "commit": "d922319a867ab8d93acffd35a7500b3f4233e638",
      "blob": "60eebbacb02fad10c66df953fbd7c546adb4464f"
    },
    "angularjs/angular.d.ts": {
      "commit": "d922319a867ab8d93acffd35a7500b3f4233e638",
      "blob": "f396593ef57f019e05495a2eeadf05d68e4f736e"
    },
    "jquery/jquery.d.ts": {
      "commit": "d922319a867ab8d93acffd35a7500b3f4233e638",
      "blob": "332ee75da76233b015ce68413208fa3c51e86eaf"
    }
  }
}
